# Generated by Django 3.2.6 on 2021-09-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['creation_date']},
        ),
    ]
